<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "api_keys" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Api keys' => 'کلید API',
  'Generate new key' => 'تولید کلید جدید',
  'Key' => 'کلید',
  'Customer' => 'مشتری',
  'Public key' => 'کلید عمومی',
  'Private key' => 'کلید خصوصی',
  'A new API access has been added:<br />Public key: {public} <br />Private key: {private}' => 'دسترسی API جدید اضافه شده است :<br />کلید عمومی: {public} <br />کلید خصوصی: {private}',
  'Your API url is: {url}' => 'Your API url is: {url}',
);
