<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "articles" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View articles' => 'نمایش مقالات',
  'Articles' => 'مقالات',
  'Published' => 'منتشر شده',
  'Unpublished' => 'منتشر نشده',
  'Article' => 'مقاله',
  'Title' => 'عنوان',
  'Slug' => 'کند',
  'Content' => 'متن',
  'Create new article' => 'ایجاد مقاله جدید',
  'My article title' => 'عنوان مقاله من',
  'my-article-title' => 'عنوان-مقاله-من',
  'Category' => 'مجموعه',
  'View article categories' => 'نمایش مجموعه های مقاله',
  'Categories' => 'مجموعه ها',
  'Article categories' => 'مجموعه های مقاله',
  'Parent' => 'مرجع',
  'Name' => 'نام',
  'Description' => 'توضیح',
  'Create new article category' => 'ایجاد مجموعه جدید مقاله',
  'My category name' => 'نام مجموعه',
  'my-category-name' => 'نام مجموعه',
  'View countries' => 'نمایش کشورها',
  'View zones' => 'نمایش مناطق',
  'Related articles' => 'مقالات مرتبط',
  'Update article' => 'بروزرسانی مقاله',
  'Update article category' => 'بروزرسانی مجموعه مقاله',
);
