<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "dashboard" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Dashboard' => 'کنترل پنل',
  'At a glance' => 'در یک نگاه',
  'Customers' => 'مشتریان',
  'More info' => 'اطلاعات بیشتر',
  'Campaigns' => 'آگهی ها',
  'No detailed info' => 'فاقد اطلاعات',
  'Lists' => 'لیست ها',
  'Segments' => 'بخش ها',
  'Subscribers' => 'مشترکین',
  'Delivery servers' => 'سرورهای تحویل',
  'Recent customer activity' => 'فعالیت های اخیر مشتری',
  'Are you sure you want to remove all activity messages?' => 'آیا مطمئن هستید که تمامی پیغام های فعالیت ها را میخواهید حذف نمایید؟',
  'Subscribers growth' => 'رشد مشترکین',
  'Lists growth' => 'رشد لیست ها',
  'Campaigns growth' => 'رشد آگهی ها',
  'Delivery vs Bounces' => 'تحویل در مقابل رد',
  'Unsubscribe growth' => 'رشد لغو اشتراک',
  'Templates' => 'قالب ها',
  'API keys' => 'API کلید',
  'Recent activity' => 'فعالیت اخیر',
  'Delivery, {n} months growth' => 'تحویل, {n} رشد ماهیانه',
  'Bounce, {n} months growth' => 'بانس, {n} رشد ماهیانه',
  '{n} months growth' => '{n} رشد ماهیانه',
  'Are you sure you want to remove all blacklisted emails?' => 'آیا مطمئن هستید که میخواهید تمامی ایمیل های لیست سیاه را حذف نمایید؟',
  'Unique subscribers' => 'Unique subscribers',
  'Total subscribers' => 'Total subscribers',
);
