<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_blacklist" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Blacklisted emails' => 'ایمیل های بلاک شده',
  'Email' => 'ایمیل',
  'Subscriber' => 'مشترکین',
  'Reason' => 'علت',
  'Import from CSV file' => 'ایمپورت از طریق فایل csv',
  'Please note, the csv file must contain a header with at least the email column.' => 'لطفا توجه داشته باشید, فایل csv باید حتما یک ستون حاوی ایمیل داشته باشد.',
  'If unsure about how to format your file, do an export first and see how the file looks.' => 'اگر در مورد چگونگی فرمت فایل خود مطمئن نیستید, این فایل را ببینید تا از نحوه صحیح آن آگاه شوید.',
  'Add a new email address to blacklist.' => 'اضافه کردن یک آدرس ایمیل جدید به لیست سیاه.',
  'Date added' => 'تاریخ اضافه شدن',
  'Your file does not contain the header with the fields title!' => 'فایل شما حاوی هدر با عنوان زمینه نمی باشد!',
  'Update blacklisted email address.' => 'بروزرسانی لیست ایمیل بلاک شده.',
);
