<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "email_templates" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Import html from url' => 'ایمپورت فایل Html از طریق آدرس لینک',
  'Upload template' => 'بارگذاری قالب',
  'Upload template archive' => 'بارگذاری قالب آرشیو شده',
  'Please see <a href="{templateArchiveHref}">this example archive</a> in order to understand how you should format your uploaded archive! Also, please note we only accept zip files.' => 'لطفا <a href="{templateArchiveHref}">آرشیو نمونه را مشاهده نمایید</a> به منظور درک چگونگی شما باید بایگانی آپلود شده خود را با فرمت مورد نظر ببینید! همچنین, توجه داشته باشید فایل باید به صورت zip باشد.',
  'Template' => 'قالب',
  'Template uid' => 'شناسه قالب',
  'Customer' => 'مشتری',
  'Name' => 'نام',
  'Content' => 'محتوا',
  'Content hash' => 'هش محتوا',
  'Create screenshot' => 'ایجاد تصویر صفحه نمایش',
  'Screenshot' => 'تصویر صفحه نمایش',
  'Inline css' => 'Inline css',
  'Minify' => 'خرد کردن',
  'Archive file' => 'فایل آرشیو',
  'The name of the template, used for you to make the difference if having to many templates.' => 'The name of the template, used for you to make the difference if having to many templates.',
  'Whether the parser should extract the css from the head of the document and inline it for each matching attribute found in the document body.' => 'Whether the parser should extract the css from the head of the document and inline it for each matching attribute found in the document body.',
  'Whether the parser should minify the template to reduce size.' => 'Whether the parser should minify the template to reduce size.',
  'Upload archive' => 'Upload archive',
  'Import html template from url' => 'Import html template from url',
  'Please note that your url must contain a valid html email template with absolute paths to resources!' => 'Please note that your url must contain a valid html email template with absolute paths to resources!',
  'Import' => 'Import',
  'My email templates' => 'My email templates',
  'Create a new email template' => 'Create a new email template',
  'Email templates' => 'Email templates',
  'Email templates gallery' => 'Email templates gallery',
  'Update email template' => 'Update email template',
  'Preview' => 'Preview',
  'You successfully updated your email template!' => 'You successfully updated your email template!',
  'Please wait while saving your template screenshot...' => 'Please wait while saving your template screenshot...',
  'Send a test email using this template' => 'Send a test email using this template',
  'Send a test email' => 'Send a test email',
  '* if multiple recipients, separate the email addresses by a comma.<br /> * the email tags will not be parsed while sending test emails.<br /> * make sure you save the template changes before you send the test.' => '* if multiple recipients, separate the email addresses by a comma.<br /> * the email tags will not be parsed while sending test emails.<br /> * make sure you save the template changes before you send the test.',
  'Send test' => 'Send test',
  'Test email successfully sent to {email}!' => 'Test email successfully sent to {email}!',
  'The template has been successfully imported!' => 'The template has been successfully imported!',
  'Unable to send the test email to {email}!' => 'Unable to send the test email to {email}!',
  'You successfully created a new email template!' => 'You successfully created a new email template!',
  'The template has been successfully copied!' => 'The template has been successfully copied!',
  'Sort order' => 'Sort order',
);
