<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_campaign_activity_map" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Campaign activity map' => 'نقشه فعالیت آگهی',
  'Decide whether to show various maps in the campaign overview area.' => 'تصمیم بگیرید که آیا برای نشان دادن نقشه های مختلف در آگهی منطقه بررسی اجمالی شود.',
  'Show opens map' => 'نمایش نقشه باز شده ها',
  'Show clicks map' => 'نمایش نقشه کلیک شده ها',
  'Opens at once' => 'باز شده های به یکباره',
  'Clicks at once' => 'کلیک شده های به یکباره',
  'Show unsubscribes map' => 'نمایش نقشه لغو اشتراک شده',
  'Unsubscribes at once' => 'لغو اشتراک به یکباره',
  'Whether to show a map with location opens in campaign overview' => 'Whether to show a map with location opens in campaign overview',
  'Whether to show a map with location clicks in campaign overview' => 'Whether to show a map with location clicks in campaign overview',
  'How many open records to load at once per ajax call? More records means more memory usage' => 'How many open records to load at once per ajax call? More records means more memory usage',
  'How many click records to load at once per ajax call? More records means more memory usage' => 'How many click records to load at once per ajax call? More records means more memory usage',
  'Whether to show a map with location from where subscribers unsubscribed in campaign overview' => 'Whether to show a map with location from where subscribers unsubscribed in campaign overview',
  'How many unsubscribe records to load at once per ajax call? More records means more memory usage' => 'How many unsubscribe records to load at once per ajax call? More records means more memory usage',
);
