<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_payment_gateway_payline" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Payline' => 'Payline',
  'Retrieve payments using payline' => 'Retrieve payments using payline',
  'Payline payment gateway' => 'Payline payment gateway',
  'sandbox' => 'sandbox',
  'live' => 'live',
  'Payline Api' => 'Payline Api',
  'Mode' => 'Mode',
  'Your payline api where the payments should go' => 'Your payline api where the payments should go',
  'Whether the payments are live or run in sanbox' => 'Whether the payments are live or run in sanbox',
  'Whether this gateway is enabled and can be used for payments processing' => 'Whether this gateway is enabled and can be used for payments processing',
  'The sort order for this gateway' => 'The sort order for this gateway',
  'You will be redirected to pay securely on payline.ir.com official website!' => 'You will be redirected to pay securely on payline.ir.com official website!',
);
