<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "extensions" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Extensions' => 'Extensions',
  'View extensions' => 'View extensions',
  'Uploaded extensions' => 'Uploaded extensions',
  'Upload extension' => 'Upload extension',
  'Name' => 'Name',
  'Description' => 'Description',
  'Version' => 'Version',
  'Author' => 'Author',
  'Website' => 'Website',
  'Extension detail page' => 'Extension detail page',
  'Core extensions' => 'Core extensions',
  'Visit website' => 'Visit website',
  'Upload extension archive.' => 'Upload extension archive.',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'The extension "{name}" has been successfully enabled!' => 'The extension "{name}" has been successfully enabled!',
  'The extension "{name}" has been successfully disabled!' => 'The extension "{name}" has been successfully disabled!',
  'Your extension has been successfully uploaded!' => 'Your extension has been successfully uploaded!',
);
