<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "languages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View available languages' => 'View available languages',
  'Languages' => 'Languages',
  'Available languages' => 'Available languages',
  'Upload language pack' => 'Upload language pack',
  'Language' => 'Language',
  'Name' => 'Name',
  'Language code' => 'Language code',
  'Region code' => 'Region code',
  'Is default language?' => 'Is default language?',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'Language packs contain executable PHP files, please check the packs before upload.' => 'Language packs contain executable PHP files, please check the packs before upload.',
  'Create new language' => 'Create new language',
  'i.e: English - United States' => 'i.e: English - United States',
  'i.e: en' => 'i.e: en',
  'i.e: us' => 'i.e: us',
  'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)' => 'The visible language name to distinct between same language but distinct regions (i.e: between English US and English GB)',
  '2 letter language code, i.e: en' => '2 letter language code, i.e: en',
  '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough' => '2 letter region code, i.e: us. Please do not fill this field unless necessary. For most of the cases, the language code is enough',
  'Whether this language is the default language for users/customers that have not set a language' => 'Whether this language is the default language for users/customers that have not set a language',
  'Update language' => 'Update language',
  'Your language pack has been successfully uploaded!' => 'Your language pack has been successfully uploaded!',
);
