<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_import" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Import' => 'Import',
  'Import subscribers into your list' => 'Import subscribers into your list',
  'Import subscribers' => 'Import subscribers',
  'CSV' => 'CSV',
  'Select file to import' => 'Select file to import',
  'Text' => 'Text',
  'Database' => 'Database',
  'Enter details' => 'Enter details',
  'Import from CSV file' => 'Import from CSV file',
  'Please note, we only accept valid CSV files that contain a header, that is the column names for the data to be imported.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.<br /> The import process might fail with some of the files, mainly because these are not correctly formatted or they contain invalid data.<br /> You should first do a test import(in a test list) and see if that goes as planned then do it for your actual list.<br /> <strong>Important</strong>: The CSV file column names will be used to create the list TAGS, if a tag does not exist, it will be created.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a csv file example.' => 'Please note, we only accept valid CSV files that contain a header, that is the column names for the data to be imported.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.<br /> The import process might fail with some of the files, mainly because these are not correctly formatted or they contain invalid data.<br /> You should first do a test import(in a test list) and see if that goes as planned then do it for your actual list.<br /> <strong>Important</strong>: The CSV file column names will be used to create the list TAGS, if a tag does not exist, it will be created.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a csv file example.',
  'Upload file' => 'Upload file',
  'Import from text file' => 'Import from text file',
  'Please note that you should list each email address on a separate line in your text file.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a text file example.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.' => 'Please note that you should list each email address on a separate line in your text file.<br /> You can also click <a href="{exampleArchiveHref}" target="_blank">here</a> to see a text file example.<br /> We also have a limit on the file size you are allowed to upload, that is {uploadLimit}.',
  'Import from external SQL database' => 'Import from external SQL database',
  'Please enter your credentials for the external database in order to start the import.' => 'Please enter your credentials for the external database in order to start the import.',
  'MySQL' => 'MySQL',
  'Server type' => 'Server type',
  'Hostname' => 'Hostname',
  'Port' => 'Port',
  'Username' => 'Username',
  'Password' => 'Password',
  'Database name' => 'Database name',
  'Table name' => 'Table name',
  'Email column' => 'Email column',
  'Ignored columns' => 'Ignored columns',
  'i.e: mysql.databaseclusters.com' => 'i.e: mysql.databaseclusters.com',
  'i.e: 3306' => 'i.e: 3306',
  'i.e: mysqlcluser' => 'i.e: mysqlcluser',
  'i.e: superprivatepassword' => 'i.e: superprivatepassword',
  'i.e: my_blog' => 'i.e: my_blog',
  'i.e: tbl_subscribers' => 'i.e: tbl_subscribers',
  'email' => 'email',
  'i.e: id, date_added, status' => 'i.e: id, date_added, status',
  'The server type, if not sure choose mysql' => 'The server type, if not sure choose mysql',
  'The hostname of your database server, it can also be the ip address' => 'The hostname of your database server, it can also be the ip address',
  'The port where your external database server is listening for connections' => 'The port where your external database server is listening for connections',
  'Your username that unique identifies yourself on the database server' => 'Your username that unique identifies yourself on the database server',
  'The password for the username' => 'The password for the username',
  'Your database name as you see it in a tool like PhpMyAdmin' => 'Your database name as you see it in a tool like PhpMyAdmin',
  'Your database table name where your emails are stored, as you see it in a tool like PhpMyAdmin' => 'Your database table name where your emails are stored, as you see it in a tool like PhpMyAdmin',
  'The column that identified the email address' => 'The column that identified the email address',
  'Which columns should we ignore and not import. Separate multiple columns by a comma' => 'Which columns should we ignore and not import. Separate multiple columns by a comma',
  'Connect and import' => 'Connect and import',
  'Text Import' => 'Text Import',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your text file has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your text file has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'Text file import progress' => 'Text file import progress',
  'Back to import options' => 'Back to import options',
  'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.' => 'From a total of {total} subscribers, so far {totalProcessed} have been processed, {successfullyProcessed} successfully and {errorProcessing} with errors. {percentage} completed.',
  'The import process is starting, please wait...' => 'The import process is starting, please wait...',
  'Checking the list for the email: "{email}"' => 'Checking the list for the email: "{email}"',
  'The email "{email}" was not found, we will try to create it...' => 'The email "{email}" was not found, we will try to create it...',
  'The email "{email}" has been successfully saved.' => 'The email "{email}" has been successfully saved.',
  'Imported {count} subscribers starting from row {rowStart} and ending with row {rowEnd}! Going further, please wait...' => 'Imported {count} subscribers starting from row {rowStart} and ending with row {rowEnd}! Going further, please wait...',
  'The import process has finished!' => 'The import process has finished!',
  'Invalid email address!' => 'Invalid email address!',
  'Failed to save the email "{email}", reason: {reason}' => 'Failed to save the email "{email}", reason: {reason}',
  'The email "{email}" has been found, we will update it.' => 'The email "{email}" has been found, we will update it.',
  'Click to export' => 'Click to export',
  'This email address is blacklisted!' => 'This email address is blacklisted!',
  'Database Import' => 'Database Import',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'Database import progress' => 'Database import progress',
  'Cannot find the "email" column in your database!' => 'Cannot find the "email" column in your database!',
  'Your database cannot be imported, a general error has been encountered: {message}!' => 'Your database cannot be imported, a general error has been encountered: {message}!',
  'CSV Import' => 'CSV Import',
  'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your CSV has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.' => 'The import process will start shortly. <br /> While the import is running it is recommended you leave this page as it is and wait for the import to finish.<br /> The importer runs in batches of {subscribersPerBatch} subscribers with a pause of {pause} seconds between the batches, therefore the import process might take a while depending on your file size and number of subscribers to import.<br /> Please note, the subscribers number is aproximate if your CSV has empty lines or ends with an empty line or it has duplicate emails(case in which the subscriber will be updated).<br /> This is a tedious process, so sit tight and wait for it to finish.',
  'CSV import progress' => 'CSV import progress',
  'Cannot find the "email" column in your file!' => 'Cannot find the "email" column in your file!',
  'The import process for list "{listName}" has successfully started, counting {rowsCount} records!' => 'The import process for list "{listName}" has successfully started, counting {rowsCount} records!',
  'Found the following column names: {columns}' => 'Found the following column names: {columns}',
  'Checking to see if the tag "{tag}" is defined in your list fields...' => 'Checking to see if the tag "{tag}" is defined in your list fields...',
  'The tag "{tag}" is already defined in your list fields.' => 'The tag "{tag}" is already defined in your list fields.',
);
