<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_pages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List pages' => 'List pages',
  'Pages' => 'Pages',
  'Select another list page to edit' => 'Select another list page to edit',
  'Subscribe form' => 'Subscribe form',
  'Pending subscribe' => 'Pending subscribe',
  'Subscription confirmed' => 'Subscription confirmed',
  'Update Profile' => 'Update Profile',
  'Unsubscribe form' => 'Unsubscribe form',
  'Unsubscribe confirmation' => 'Unsubscribe confirmation',
  'Subscribe confirm email' => 'Subscribe confirm email',
  'Unsubscribe confirm email' => 'Unsubscribe confirm email',
  'Your subscribe form url is:' => 'Your subscribe form url is:',
  'Preview it now!' => 'Preview it now!',
  'List' => 'List',
  'Type' => 'Type',
  'Content' => 'Content',
);
