<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_subscribers" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List subscribers' => 'List subscribers',
  'Subscribers' => 'Subscribers',
  'Add a new subscriber to your list.' => 'Add a new subscriber to your list.',
  'confirmed' => 'confirmed',
  'unconfirmed' => 'unconfirmed',
  'unsubscribed' => 'unsubscribed',
  'Subscriber' => 'Subscriber',
  'List' => 'List',
  'Unique id' => 'Unique id',
  'Email' => 'Email',
  'Source' => 'Source',
  'Ip Address' => 'Ip Address',
  'blacklisted' => 'blacklisted',
  'Are you sure you want to unsubscribe this subscriber?' => 'Are you sure you want to unsubscribe this subscriber?',
  'Your mail list subscribers' => 'Your mail list subscribers',
  'Bulk action from source' => 'Bulk action from source',
  'With selected:' => 'With selected:',
  'Subscribe' => 'Subscribe',
  'Unsubscribe' => 'Unsubscribe',
  'Delete' => 'Delete',
  'Found {count} subscribers.' => 'Found {count} subscribers.',
  'Match the subscribers added here against the ones existing in the list and make a bulk action against them!' => 'Match the subscribers added here against the ones existing in the list and make a bulk action against them!',
  'Please note, this is not the list import ability, for list import go to your list overview, followed by Tools box followed by the Import box.' => 'Please note, this is not the list import ability, for list import go to your list overview, followed by Tools box followed by the Import box.',
  'From file' => 'From file',
  'From text' => 'From text',
  'Action' => 'Action',
  'Bulk action from CSV file, one email address per row and/or separated by a comma.' => 'Bulk action from CSV file, one email address per row and/or separated by a comma.',
  'Bulk action from text area, one email address per line and/or separated by a comma.' => 'Bulk action from text area, one email address per line and/or separated by a comma.',
  'For all the subscribers found in file/text area take this action!' => 'For all the subscribers found in file/text area take this action!',
  'Action completed, {count} subscribers were affected!' => 'Action completed, {count} subscribers were affected!',
  'Please confirm your unsubscription' => 'Please confirm your unsubscription',
  'Please check your email and click on the provided unsubscribe link.' => 'Please check your email and click on the provided unsubscribe link.',
  'The subscriber having the email address "{email}" has been successfully unsubscribed from the "{listName}" list!' => 'The subscriber having the email address "{email}" has been successfully unsubscribed from the "{listName}" list!',
  'Update existing list subscriber.' => 'Update existing list subscriber.',
  'Sorry, but there are no subscribers to show right now.' => 'Sorry, but there are no subscribers to show right now.',
  'Subscribe back' => 'Subscribe back',
  'Are you sure you want to subscribe back this unsubscriber?' => 'Are you sure you want to subscribe back this unsubscriber?',
  'The subscriber having the email address "{email}" has been successfully removed from the "{listName}" list!' => 'The subscriber having the email address "{email}" has been successfully removed from the "{listName}" list!',
  'Confirm subscriber' => 'Confirm subscriber',
  'Are you sure you want to confirm this subscriber?' => 'Are you sure you want to confirm this subscriber?',
);
