<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_fields" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List custom fields' => 'List custom fields',
  'Custom fields' => 'Custom fields',
  'Value' => 'Value',
  'Field' => 'Field',
  'Subscriber' => 'Subscriber',
  'This email address is already registered in this list!' => 'This email address is already registered in this list!',
  'Text field' => 'Text field',
  'Type' => 'Type',
  'List' => 'List',
  'Label' => 'Label',
  'Tag' => 'Tag',
  'Default value' => 'Default value',
  'Help text' => 'Help text',
  'Required' => 'Required',
  'Visibility' => 'Visibility',
  'This is what your subscribers will see above the input field.' => 'This is what your subscribers will see above the input field.',
  'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]' => 'The tag must be unique amoung the list tags. It must start with a letter, end with a letter or number and contain only alpha-numeric chars and underscores, all uppercased. The tag can be used in your templates like: [TAGNAME]',
  'In case this field is not required and you need a default value for it.' => 'In case this field is not required and you need a default value for it.',
  'If you need to describe this field to your subscribers.' => 'If you need to describe this field to your subscribers.',
  'Whether this field must be filled in in order to submit the subscription form.' => 'Whether this field must be filled in in order to submit the subscription form.',
  'Hidden fields are not shown to subscribers.' => 'Hidden fields are not shown to subscribers.',
  'Decide the order of the fields shown in the form.' => 'Decide the order of the fields shown in the form.',
  'Are you sure you want to remove this field? There is no coming back from this after you save the changes.' => 'Are you sure you want to remove this field? There is no coming back from this after you save the changes.',
  'Your mail lists custom fields' => 'Your mail lists custom fields',
  'Add text field' => 'Add text field',
  'Add dropdown field' => 'Add dropdown field',
  'Add multiselect field' => 'Add multiselect field',
  'New text field' => 'New text field',
  'New dropdown field' => 'New dropdown field',
  'Dropdown options' => 'Dropdown options',
  'Add new' => 'Add new',
  'Option' => 'Option',
  'Name' => 'Name',
  'Is default' => 'Is default',
  'Are you sure you want to remove this option? There is no coming back from this after you save the changes.' => 'Are you sure you want to remove this option? There is no coming back from this after you save the changes.',
  'New multiselect field' => 'New multiselect field',
);
