<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_segments" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List segments' => 'List segments',
  'Segments' => 'Segments',
  'Your mail list segments' => 'Your mail list segments',
  'Create a new list segment' => 'Create a new list segment',
  'any' => 'any',
  'all' => 'all',
  'Segment' => 'Segment',
  'List' => 'List',
  'Name' => 'Name',
  'Operator match' => 'Operator match',
  'Subscribers count' => 'Subscribers count',
  'Defined conditions:' => 'Defined conditions:',
  'Add condition' => 'Add condition',
  'Subscribers matching your segment:' => 'Subscribers matching your segment:',
  'Condition' => 'Condition',
  'Operator' => 'Operator',
  'Field' => 'Field',
  'Value' => 'Value',
  'is' => 'is',
  'is not' => 'is not',
  'contains' => 'contains',
  'not contains' => 'not contains',
  'starts with' => 'starts with',
  'ends with' => 'ends with',
  'is greater than' => 'is greater than',
  'is less than' => 'is less than',
  'Remove condition' => 'Remove condition',
  'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!' => 'A new segment called "{segmentName}" has been added to the list "{listName}" successfully!',
  'Update list segment' => 'Update list segment',
  'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!' => 'The segment called "{segmentName}" belonging to the list "{listName}" has been successfully updated!',
  ' List segments' => ' List segments',
  'This segment contains {count} subscribers' => 'This segment contains {count} subscribers',
  'Sorry, but there are no subscribers matching your segment.' => 'Sorry, but there are no subscribers matching your segment.',
  'The segment {segmentName} belonging to the list "{listName}" has been successfully deleted!' => 'The segment {segmentName} belonging to the list "{listName}" has been successfully deleted!',
  'Your list segment was successfully copied!' => 'Your list segment was successfully copied!',
);
