<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "orders" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View orders' => 'مشاهده سفارشات',
  'Orders' => 'سفارشات',
  'Order' => 'سفارش',
  'Order no.' => 'شماره سفارش.',
  'Customer' => 'مشتری',
  'Plan' => 'پلان',
  'Promo code' => 'کد هدیه یا کد تخفیف',
  'Tax' => 'مالیات',
  'Currency' => 'پول',
  'Subtotal' => 'جمع جزء',
  'Tax percent' => 'درصد مالیات',
  'Tax value' => 'مقدار مالیات',
  'Discount' => 'تخفیف',
  'Total' => 'جمع کل',
  'Create order' => 'ایجاد سفارش',
  'Customer, autocomplete enabled' => 'مشتری, تکمیل خودکار را فعال کنید',
  'Plan, autocomplete enabled' => 'پلان, تکمیل خودکار را فعال کنید',
  'Promo code, autocomplete enabled' => 'کد هدیه, تکمیل خودکار را فعال کنید',
  'The customer this order applies to, autocomplete enabled' => 'سفارش این مشتری شامل, تکمیل خودکار را فعال کنید',
  'The price plan included in this order, autocomplete enabled' => 'پلان قیمت موجود در این سفارش, تکمیل خودکار را فعال کنید',
  'The promo code applied to this order, autocomplete enabled' => 'The promo code applied to this order, autocomplete enabled',
  'Note' => 'Note',
  'If you have particular notes about this order, please type them here...' => 'If you have particular notes about this order, please type them here...',
  'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.' => 'Please note that any order added/changed from this area is not verified nor it goes through a payment gateway.',
  'Updating orders from this area is useful for offline orders mostly or for payment corrections.' => 'Updating orders from this area is useful for offline orders mostly or for payment corrections.',
  'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.' => 'If the order is incomplete, pending or due and changed to complete, the customer will be affected and the price plan will be assigned properly.',
  'View your orders' => 'نمایش سفارشات من',
  'Payment method' => 'روش پرداخت',
  'Enter your promo code here' => 'کد هدیه یا کد تخفیف را وارد نمایید',
  'Amount due' => 'مقدار',
  'due' => 'دلیل',
  'View your order' => 'نمایش سفارشات من',
  'This order applies for the "{planName}" pricing plan.' => 'This order applies for the "{planName}" pricing plan.',
  'Notes' => 'یادداشت',
  'Transaction info' => 'اطلاعات تراکنش',
  'Transaction' => 'تراکنش',
  'Transaction uid' => 'UID تراکنش',
  'Payment gateway name' => 'نام درگاه پرداخت',
  'Payment gateway transaction' => 'تراکنش درگاه پرداخت',
  'Payment gateway response' => 'پاسخ درگاه پرداخت',
  'Amount' => 'مقدار',
  'Status' => 'وضعیت',
  'Email invoice' => 'ایمیل کردن فاکتور',
  'View invoice' => 'نمایش فاکتور',
  'Back to orders' => 'برگشت به سفارشات',
  'Invoice' => 'قاکتور',
  'Total due' => 'کل',
  'Reference' => 'ارجاع',
  'Billing date' => 'تاریخ صدور صورت حساب',
  'Due date' => 'موعد مقرر',
  'Payment from' => 'پرداخت از',
  'Payment to' => 'پرداخت به',
  'Quantity' => 'تعداد',
  'Price' => 'قیمت',
  'Page' => 'صفحه',
  'of' => 'از',
  'pending' => 'معلق',
  'Update order' => 'بروز رسانی سفارش',
  'View order' => 'نمایش سفارش',
  'Update this order' => 'بروز رسانی این سفارش',
  'Hello {name}' => 'Hello {name}',
  'Attached is your order invoice with reference number: {ref}' => 'Attached is your order invoice with reference number: {ref}',
  'If you have any questions regarding this invoice, please contact us.' => 'If you have any questions regarding this invoice, please contact us.',
  'Your requested invoice - {ref}' => 'Your requested invoice - {ref}',
  'The invoice has been successfully emailed!' => 'The invoice has been successfully emailed!',
  'As requested, attached is your order invoice with reference number: {ref}' => 'As requested, attached is your order invoice with reference number: {ref}',
  'Paid' => 'پرداخت شده',
);
