<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "price_plans" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View price plans' => 'نمایش پلان قیمت',
  'Price plans' => 'پلان قیمت',
  'Plan' => 'پلان',
  'Plan uid' => 'پلان uid',
  'Customer group' => 'گروه مشتری',
  'Name' => 'نام',
  'Price' => 'قیمت',
  'Description' => 'توضیحات',
  'Recommended' => 'توصیه شده',
  'Create new price plan' => 'ایجاد پلان قیمت جدید',
  'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits' => 'The group where the customer will be moved after purchasing this plan. Make sure the group has proper permissions and limits',
  'The price plan name, used in customer display area, orders, etc' => 'The price plan name, used in customer display area, orders, etc',
  'The amount the customers will be charged when buying this plan' => 'The amount the customers will be charged when buying this plan',
  'A detailed description about the price plan features' => 'A detailed description about the price plan features',
  'Whether this plan has the recommended badge on it' => 'Whether this plan has the recommended badge on it',
  'Available price plans' => 'پلان قیمت در دسترس',
  'Select payment method' => 'انتخاب دروازه پرداخت',
  'Payment gateway selection' => 'انتخاب دروازه پرداخت',
  'Proceed to payment' => 'اقدام به پرداخت',
  'Price plans payment' => 'پرداخت پلان قیمت',
  'You have selected the "{planName}" pricing plan.' => 'You have selected the "{planName}" pricing plan.',
  'Place offline order' => 'سفارش آفلاین',
  'Apply code' => 'اعمال کد',
  'Price plan' => 'پلان قیمت',
  'Submit payment' => 'پرداخت',
  'The provided promotional code does not exists anymore!' => 'The provided promotional code does not exists anymore!',
  'The promo code has been successfully applied!' => 'The promo code has been successfully applied!',
  'Update price plan' => 'بروزرسانی پلان قیمت',
);
