<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "promo_codes" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'fixed amount' => 'مقدار ثابت',
  'percentage' => 'در صد',
  'View job promo codes' => 'مشخصات کد هدیه یا کد تخفیف',
  'Promo codes' => 'کد هدیه یا کد تخفیف',
  'Jobs' => 'مشاغل',
  'Code' => ' کد تخفیف',
  'Type' => 'نوع',
  'Discount' => 'مقدار تخفیف',
  'Total amount' => 'مقدار کل',
  'Total usage' => 'مجموع استفاده',
  'Customer usage' => 'مشتری استفده کننده',
  'Date start' => 'تاریخ شروع',
  'Date end' => 'تاریخ پایان',
  'Create new promo code' => 'ایجاد کد تخفیف جدید',
  'i.e: FREE100' => 'کد تخفیف را اینجا وارد نمایید',
  'i.e: 10' => 'i.e: 10',
  'i.e: 30' => 'i.e: 30',
  'i.e: 1' => 'i.e: 1',
  'i.e: {date}' => 'i.e: {date}',
  'i.e: 2015-01-06' => 'i.e: 2015-01-06',
  'i.e: 2015-02-05' => 'i.e: 2015-02-05',
  'The promotional code' => 'The promotional code',
  'The type of the promotional code' => 'The type of the promotional code',
  'The discount received after applying this promotional code' => 'The discount received after applying this promotional code',
  'The amount of the price plan in order for this promotional code to apply' => 'The amount of the price plan in order for this promotional code to apply',
  'The maximum number of usages for this promotional code. Set it to 0 for unlimited' => 'The maximum number of usages for this promotional code. Set it to 0 for unlimited',
  'How many times a customer can use this promotional code. Set it to 0 for unlimited' => 'How many times a customer can use this promotional code. Set it to 0 for unlimited',
  'The start date for this promotional code' => 'The start date for this promotional code',
  'The end date for this promotional code' => 'The end date for this promotional code',
  'Update promo code' => 'بروز رسانی کد تخفیف',
  'i.e: 2015-01-08' => 'i.e: 2015-01-08',
  'i.e: 2015-02-07' => 'i.e: 2015-02-07',
  'i.e: 2015-03-09' => 'i.e: 2015-03-09',
  'i.e: 2015-04-08' => 'i.e: 2015-04-08',
  'i.e: 2015-03-23' => 'i.e: 2015-03-23',
  'i.e: 2015-04-22' => 'i.e: 2015-04-22',
  'i.e: 2015-03-24' => 'i.e: 2015-03-24',
  'i.e: 2015-04-23' => 'i.e: 2015-04-23',
  'i.e: 2015-03-30' => 'i.e: 2015-03-30',
  'i.e: 2015-04-29' => 'i.e: 2015-04-29',
  'i.e: 2015-04-04' => 'i.e: 2015-04-04',
  'i.e: 2015-05-04' => 'i.e: 2015-05-04',
);
