<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "themes" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View themes' => 'View themes',
  'Themes' => 'Themes',
  'Available themes' => 'Available themes',
  'Upload theme' => 'Upload theme',
  'Name' => 'Name',
  'Description' => 'Description',
  'Version' => 'Version',
  'Author' => 'Author',
  'Website' => 'Website',
  'Extension detail page' => 'Extension detail page',
  'Upload theme archive.' => 'Upload theme archive.',
  'Please note that only zip files are allowed for upload.' => 'Please note that only zip files are allowed for upload.',
  'Theme detail page' => 'Theme detail page',
);
