<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "tracking_domains" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2014 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View tracking domains' => 'View tracking domains',
  'Tracking domains' => 'Tracking domains',
  'Domain' => 'Domain',
  'Customer' => 'Customer',
  'Name' => 'Name',
  'Create new tracking domain' => 'Create new tracking domain',
  'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!' => 'Please note that because of the way DNS servers work, you need to add a subdomain like tracking.your-domain.com as a DNS CNAME record and point it to {currentDomain}!',
  'tracking.your-domain.com' => 'tracking.your-domain.com',
  'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.' => 'Please note, in order for this feature to work this (sub)domain needs a dedicated IP address, otherwise all defined CNAMES for it will point to the default domain on this server.',
  'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!' => 'If you do not use a dedicated IP address for this domain only or you are not sure you do so, do not use this feature!',
  'Cannot find a valid CNAME record for {domainName}! Remember, the CNAME of {domainName} must point to {currentDomain}!' => 'Cannot find a valid CNAME record for {domainName}! Remember, the CNAME of {domainName} must point to {currentDomain}!',
  'Update tracking domain' => 'Update tracking domain',
);
