<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "users" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View users' => 'نمایش کاربران',
  'Users' => 'کاربران',
  'User' => 'کاربر',
  'Language' => 'زبان',
  'First name' => 'نام',
  'Last name' => 'نام خانوادگی',
  'Email' => 'ایمیل',
  'Password' => 'پسورد',
  'Timezone' => 'Timezone',
  'Avatar' => 'آواتار',
  'New avatar' => 'آواتار جدید',
  'Removable' => 'قابل جا به جایی',
  'Confirm email' => 'تایید ایمیل',
  'Confirm password' => 'تایید پسورد',
  'Create new user' => 'ایجاد کاربر جدید',
  'Update account' => 'بروزرسانی اکانت',
  'Update your account data.' => 'بروز رسانی اطلاعات حساب.',
  'Please login' => 'لطفا وارد شوید',
  'Remember me' => 'مرا به خاطر بسپار',
  'Forgot password?' => 'فراموشی پسورد؟',
  'Update user' => 'بروزرسانی کاربر',
  'You are impersonating the customer {customerName}.' => 'شما در حال جعل هویت مشتری {customerName} می باشید.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'لطفا کلیک نمایید {linkBack} تا خارج شوید.',
  'Retrieve a new password for your account.' => 'Retrieve a new password for your account.',
  'Request' => 'Request',
  'Reset key' => 'Reset key',
  'Ip address' => 'Ip address',
  'Invalid login credentails.' => 'Invalid login credentails.',
  'Group' => 'Group',
);
