<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "user_groups" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2015 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View user groups' => 'View user groups',
  'User groups' => 'User groups',
  'Group' => 'Group',
  'Name' => 'Name',
  'Users count' => 'Users count',
);
